"""
Saarthi Finance — Database Seed Script.

Populates initial personas, goals, alerts, and historical transactions.
Loads from data/seed/ and data/processed/ generated by Laptop 3 ML layer.
Can be executed directly via:
    python -m app.seed
or imported and run via seed_database(db).
"""

from __future__ import annotations

import csv
import datetime
import json
import os
from pathlib import Path
from sqlalchemy.orm import Session

from app.database import engine, SessionLocal, Base
from app.models.customer import Customer
from app.models.transaction import Transaction
from app.models.goal import Goal
from app.models.alert import Alert


def find_data_dirs() -> tuple[Path | None, Path | None]:
    """Locate data/seed and data/processed directories across possible paths."""
    candidates = [
        Path(__file__).resolve().parent.parent.parent.parent / "data",
        Path(__file__).resolve().parent.parent.parent / "data",
        Path(__file__).resolve().parent.parent / "data",
        Path("data"),
        Path("../../data"),
    ]
    seed_dir = None
    processed_dir = None
    for c in candidates:
        if not seed_dir and (c / "seed").is_dir():
            seed_dir = c / "seed"
        if not processed_dir and (c / "processed").is_dir():
            processed_dir = c / "processed"
        if seed_dir and processed_dir:
            break
    return seed_dir, processed_dir


def seed_database(db: Session, force: bool = False) -> None:
    """Populate database with synthetic demo data if empty or forced."""
    Base.metadata.create_all(bind=engine)

    existing_count = db.query(Customer).count()
    if existing_count > 0 and not force:
        return

    if force:
        db.query(Alert).delete()
        db.query(Goal).delete()
        db.query(Transaction).delete()
        db.query(Customer).delete()
        db.commit()

    seed_dir, processed_dir = find_data_dirs()

    # Load ML health scores & dashboards if available
    health_scores_map = {}
    if processed_dir and (processed_dir / "health_scores.json").is_file():
        try:
            with open(processed_dir / "health_scores.json", encoding="utf-8") as f:
                hs_list = json.load(f)
                for item in hs_list:
                    health_scores_map[item.get("customer_id")] = item
        except Exception:
            pass

    # Load loans map if available
    loans_map: dict[str, dict] = {}
    if seed_dir and (seed_dir / "loans.csv").is_file():
        try:
            with open(seed_dir / "loans.csv", encoding="utf-8") as f:
                for row in csv.DictReader(f):
                    cid = row["customer_id"]
                    if cid not in loans_map:
                        loans_map[cid] = {"total_emi": 0.0, "total_debt": 0.0, "has_overdue": False}
                    loans_map[cid]["total_emi"] += float(row.get("emi_amount", 0))
                    loans_map[cid]["total_debt"] += float(row.get("outstanding_amount", 0))
                    if "overdue" in row.get("repayment_status", ""):
                        loans_map[cid]["has_overdue"] = True
        except Exception:
            pass

    # 1. Customers
    customers = []
    if seed_dir and (seed_dir / "customers.csv").is_file():
        with open(seed_dir / "customers.csv", encoding="utf-8") as f:
            for row in csv.DictReader(f):
                cid = row["customer_id"]
                hs = health_scores_map.get(cid, {})
                score = hs.get("score")
                risk = hs.get("label", "Stable").lower()
                loan_info = loans_map.get(cid, {"total_emi": 0.0, "total_debt": 0.0})

                c = Customer(
                    id=cid,
                    name=row["name"],
                    city=row["city"],
                    state=row["state"],
                    preferred_language=row.get("preferred_language", "hi"),
                    phone=f"98XXXXX{cid[-3:]}",
                    age=int(row["age"]) if row.get("age") else 30,
                    occupation=row.get("occupation", "Professional"),
                    dependents=int(row["dependents"]) if row.get("dependents") else 2,
                    monthly_income=float(row.get("monthly_income", 30000)),
                    income_source="Salary" if "Salary" in row.get("customer_segment", "") else "Business / Wages",
                    income_stability="stable" if risk in ("stable", "excellent", "good") else "variable",
                    existing_emi=loan_info["total_emi"],
                    total_debt=loan_info["total_debt"],
                    credit_score_band="Good" if score and score > 70 else "Fair" if score and score > 50 else "Needs Attention",
                    emergency_fund=float(row.get("monthly_income", 30000)) * (1.5 if risk == "stable" else 0.2),
                    financial_health_score=float(score) if score is not None else 70.0,
                    risk_level=risk,
                    password_hash="$2b$12$e8Y6l14vJ6nU0v6Gk8zMueZzG8vM7eZ0K8vM7eZ0K8vM7eZ0K8vM7",
                )
                customers.append(c)
    else:
        # Fallback personas if CSV not present
        customers = [
            Customer(
                id="cust_001",
                name="Ananya Verma",
                city="Indore",
                state="Madhya Pradesh",
                preferred_language="hi",
                phone="98XXXXX001",
                age=28,
                occupation="School Teacher",
                dependents=2,
                monthly_income=58000.0,
                income_source="Salary",
                income_stability="stable",
                existing_emi=9500.0,
                total_debt=145000.0,
                credit_score_band="Good",
                emergency_fund=60000.0,
                financial_health_score=81.0,
                risk_level="stable",
                password_hash="$2b$12$e8Y6l14vJ6nU0v6Gk8zMueZzG8vM7eZ0K8vM7eZ0K8vM7eZ0K8vM7",
            ),
            Customer(
                id="cust_002",
                name="Ramesh Patil",
                city="Nashik",
                state="Maharashtra",
                preferred_language="mr",
                phone="98XXXXX002",
                age=35,
                occupation="Auto Driver",
                dependents=4,
                monthly_income=32000.0,
                income_source="Daily Wages / Gig",
                income_stability="variable",
                existing_emi=13500.0,
                total_debt=153000.0,
                credit_score_band="Needs Attention",
                emergency_fund=3000.0,
                financial_health_score=28.0,
                risk_level="at risk",
                password_hash="$2b$12$e8Y6l14vJ6nU0v6Gk8zMueZzG8vM7eZ0K8vM7eZ0K8vM7eZ0K8vM7",
            ),
        ]
    db.add_all(customers)
    db.commit()

    # 2. Goals
    goals = []
    if seed_dir and (seed_dir / "goals.csv").is_file():
        with open(seed_dir / "goals.csv", encoding="utf-8") as f:
            for row in csv.DictReader(f):
                gid = row.get("goal_id", f"g_{row['customer_id']}")
                gtype = row.get("goal_type", "emergency_fund").lower().replace(" ", "_")
                t_date = row.get("target_date", "2026-12-31")
                try:
                    parsed_date = datetime.date.fromisoformat(t_date)
                except Exception:
                    parsed_date = datetime.date(2026, 12, 31)

                goal = Goal(
                    id=gid,
                    customer_id=row["customer_id"],
                    type=gtype,
                    name=row.get("goal_type", "Savings Goal"),
                    target_amount=float(row.get("target_amount", 50000)),
                    current_amount=float(row.get("current_amount", 10000)),
                    target_date=parsed_date,
                    monthly_contribution=float(row.get("monthly_contribution", 2000)),
                )
                goals.append(goal)
    else:
        goals = [
            Goal(
                id="g001",
                customer_id="cust_001",
                type="emergency_fund",
                name="Emergency Fund",
                target_amount=100000.0,
                current_amount=32000.0,
                target_date=datetime.date(2026, 12, 31),
                monthly_contribution=5000.0,
            ),
        ]
    db.add_all(goals)
    db.commit()

    # 3. Alerts
    alerts = []
    if processed_dir and (processed_dir / "alerts.json").is_file():
        try:
            with open(processed_dir / "alerts.json", encoding="utf-8") as f:
                alerts_data = json.load(f)
                for a in alerts_data:
                    alerts.append(
                        Alert(
                            id=a["id"],
                            customer_id=a["customer_id"],
                            type=a.get("type", "cash_flow"),
                            severity=a.get("severity", "medium"),
                            title=a.get("title", "Financial Alert"),
                            description=a.get("description", ""),
                            evidence=a.get("evidence", ""),
                            action=a.get("action", "Review your budget"),
                            action_label=a.get("action_label", "Review Details"),
                        )
                    )
        except Exception:
            pass

    if not alerts:
        alerts = [
            Alert(
                id="alert_001",
                customer_id="cust_001",
                type="cash_flow",
                severity="medium",
                title="Monthly expenses rising steadily",
                description="Your household spending increased by 12% over the last two months.",
                evidence="Aug expenses: ₹31,500 → Sep expenses: ₹31,800",
                action="Review your recurring expenses and identify where you can cut back.",
                action_label="Review Expenses",
            ),
            Alert(
                id="alert_002",
                customer_id="cust_002",
                type="missed_emi_risk",
                severity="critical",
                title="High EMI-to-income burden (42%)",
                description="With overdue loan obligations, taking on new debt is not recommended.",
                evidence="EMI ₹13,500 on ₹32,000 monthly income",
                action="Speak with a certified financial counsellor to restructure debt.",
                action_label="Free Debt Counselling",
            ),
        ]
    db.add_all(alerts)
    db.commit()

    # 4. Transactions
    if seed_dir and (seed_dir / "transactions.csv").is_file():
        with open(seed_dir / "transactions.csv", mode="r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            txn_objects = []
            for idx, row in enumerate(reader, start=1):
                txn_id = row.get("transaction_id") or f"t_{row.get('customer_id', 'cust')}_{idx:04d}"
                raw_type = row.get("transaction_type") or row.get("type") or "debit"
                txn = Transaction(
                    id=txn_id,
                    customer_id=row["customer_id"],
                    date=datetime.date.fromisoformat(row["date"]),
                    merchant=row.get("merchant", "General Merchant"),
                    category=row.get("category", "General"),
                    amount=float(row.get("amount", 0)),
                    type=raw_type.strip().lower(),
                    channel=row.get("channel", "UPI"),
                    recurring=str(row.get("recurring", "")).lower() in ("true", "1", "yes"),
                    description=row.get("description", ""),
                )
                txn_objects.append(txn)
            db.add_all(txn_objects)
            db.commit()


if __name__ == "__main__":
    db = SessionLocal()
    try:
        seed_database(db, force=True)
        print("Database seeded successfully with all personas, goals, alerts, and transactions.")
    finally:
        db.close()
